### ISSUE TITLE
`no instance of constructor "smartview" matches the argument list` error in vscode

### ISSUE THREAD

**Issue by leoyoung07** [saucer/saucer#12]
### ✍️ Bug Description

cmake could build with no error, but vscode shows an error in editor:
![image](https://github.com/saucer/saucer/assets/8199708/f37f1d57-3dc0-4551-b8ae-28e1d3f28868)

### 🔁 Steps to reproduce

I created a project following the tutorial on Windows 11: [https://saucer.github.io/docs/getting-started/basic-app](https://saucer.github.io/docs/getting-started/basic-app).
I can **build the project with no error using cmake**: 
```bash
C:\dev\cmake-3.27.5-windows-x86_64\bin\cmake.EXE --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_TOOLCHAIN_FILE:STRING=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET:STRING=x64-windows -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE "-DCMAKE_C_COMPILER:FILEPATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\x64\bin\clang-cl.exe" "-DCMAKE_CXX_COMPILER:FILEPATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\x64\bin\clang-cl.exe" -SC:/LeoProjects/saucer-test -Bc:/LeoProjects/saucer-test/build -G "Visual Studio 17 2022" -T ClangCL,host=x64 -A x64
```
But vscode shows an error in editor: `no instance of constructor "smartview" matches the argument list`.
My `c_cpp_properties.json`:
```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/build/_deps/saucer-src/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.22621.0",
            "compilerPath": "cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++20",
            "intelliSenseMode": "windows-msvc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

### 🛸 Saucer Version

v2.1.0

### 🖥️ Operating System

Windows 11

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing bug report for this issue
- [X] the problem does occur with the reproduction steps I provided
- [X] what I described is indeed a problem

**Comment by Curve** [comment]
This seems to be windows related, what's your exact compiler version?

**Comment by Curve** [comment]
This might be related: https://github.com/microsoft/vscode-cpptools/issues/2912

**Comment by Curve** [comment]
I could reproduce this with some basic code that uses concepts, the issue lies within the C/C++ VSCode extension as their language server is not able to deduce concepts correctly.

Relevant issue: https://github.com/microsoft/vscode-cpptools/issues/8132

**Comment by Curve** [comment]
I've filed an additional issue for you here: https://github.com/microsoft/vscode-cpptools/issues/11624

There is nothing I can do to fix this, it's on the C/C++ Extension. As mentioned earlier I'd recommend using clangd instead.

**Comment by leoyoung07** [comment]
> I could reproduce this with some basic code that uses concepts, the issue lies within the C/C++ VSCode extension as their language server is not able to deduce concepts correctly.
> 
> Another related issue: [microsoft/vscode-cpptools#8132](https://github.com/microsoft/vscode-cpptools/issues/8132)
> 
> I would strongly recommend to use the [clangd extension](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) as it suffers from way less bugs imho.

Thanks for the suggestion, I'll try the clangd extension later.

**Comment by Curve** [comment]
> > I could reproduce this with some basic code that uses concepts, the issue lies within the C/C++ VSCode extension as their language server is not able to deduce concepts correctly.
> > Another related issue: [microsoft/vscode-cpptools#8132](https://github.com/microsoft/vscode-cpptools/issues/8132)
> > I would strongly recommend to use the [clangd extension](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) as it suffers from way less bugs imho.
> 
> Thanks for the suggestion, I'll try the clangd extension later.

Make sure you're properly [exporting compile commands](https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html) when using clangd (this may require clang-cl as well)
