### ISSUE TITLE
CSS font-face requests are not filtered by webview2

### ISSUE THREAD

**Issue by leoyoung07** [saucer/saucer#13]
### ✍️ Bug Description

CSS font-face files can not be served.

### 🔁 Steps to reproduce

1. create an index.html file(you don't need the real `fabric-icons-1-4d521695.woff` file, because the request won't success):
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <title>React App</title>
        <style>
            @font-face {
                font-family: "FabricMDL2Icons-1";
                src: url(/fonts/fluentui/fabric-icons-1-4d521695.woff)
                    format("woff");
            }
        </style>
    </head>
    <body>
        <i style="font-family: 'FabricMDL2Icons-1';">a</i>
    </body>
</html>
```
2. embed the html with `saucer embed` command
3. serve the embedded html:
```c++
    smartview.embed(saucer::embedded::all());
    smartview.serve("index.html");
    smartview.show();              // Show the smartview
    smartview.set_dev_tools(true); // Enable dev tools
    smartview.run();               // And finally enter the run-loop.
```
4. add a breakpoint in `saucer-src\src\webview.webview2.impl.cpp` line 56:
![image](https://github.com/saucer/saucer/assets/8199708/fcdd2ec2-790e-430c-bab8-de76105527aa)
5. compile and debug the app
6. the breakpoint won't be hitted when requesting the font file and the request will fail with an `CORS policy` error.
7. inspect network request in the DevTools:
![image](https://github.com/saucer/saucer/assets/8199708/15bdc765-cc76-4ae6-a15b-a6b791bd93d2)
![image](https://github.com/saucer/saucer/assets/8199708/4ba247b1-ab1b-4fbd-bb7d-daae0f194b9c)

### ❔ Expected behavior

CSS font-face requests should be filtered by webview2 and served with the embedded files.

### 🛸 Saucer Version

v2.1.0

### 🖥️ Operating System

Windows 11

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing bug report for this issue
- [X] the problem does occur with the reproduction steps I provided
- [X] what I described is indeed a problem

**Comment by leoyoung07** [comment]
WebView2 version: 119.0.2151.44
UA: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0'

**Comment by Curve** [comment]
This seems like an issue with the webview2 custom schemes, I'll take a look if it works with the old method

**Comment by Curve** [comment]
Was indeed the scheme, this is now fixed. Will put out a release now ^^

**Comment by Curve** [comment]
https://github.com/saucer/saucer/releases/tag/v2.1.1
