### ISSUE TITLE
Does it only support 60 frames?

### ISSUE THREAD

**Issue by daironxuan** [saucer/saucer#17]
### ✍️ Bug Description

**I found that the frame rate is 60, can I set a higher frame rate?**

### 🔁 Steps to reproduce

.

### ❔ Expected behavior

.

### 👀 Screenshots

.

### 🛸 Saucer Version

2.2.0

### 🖥️ Operating System

Linux

### 🖥️ Distribution

Linux

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing bug report for this issue
- [X] the problem does occur with the reproduction steps I provided
- [X] what I described is indeed a problem

**Comment by daironxuan** [comment]
```c++
#include <saucer/smartview.hpp>

int main() {
    saucer::smartview smartview;         // Instantiate smartview
    smartview.set_title("Hello World!"); // Set the window title to "Hello World!"
    smartview.set_size(800, 600);
    // Expose a synchronous native function "add_ten" using the default serializer
    smartview.expose("add_ten", [](int i)
    {
        return i + 10;
    });
    smartview.set_url("https://www.testufo.com/"); // Navigate to www.testufo.com
    smartview.show();                        // Show the smartview
    saucer::smartview<saucer::serializers::glaze>::run();                      // And finally enter the run-loop.
    return 0;
}
```

**Comment by Curve** [comment]
FYI: You don't need to explicitly specify glaze as the serializer in your code snippet above.


This issue may be relevant for Windows: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3045

https://bugreports.qt.io/browse/QTBUG-76006 seems to indicate that qtwebengine automatically syncs to the display refresh rate

I will do some tests later to confirm the latter

**Comment by daironxuan** [comment]
- Yes, I should smartview.run()

- I am also looking for related information about Qt WebView and I am also reading your project code.

- See if we can find something useful.

**Comment by Curve** [comment]
> * Yes, I should smartview.run()
> 
>     * I am also looking for related information about Qt WebView and I am also reading your project code.
> 
>     * See if we can find something useful.

You can control the Chromium FPS Limit through chrome flags apparently, I'll add a way to specify the chrome flags in the `saucer::options` later

**Comment by daironxuan** [comment]
```c++
namespace saucer
{
    window::window(const options &options) : m_impl(std::make_unique<impl>())
    {
        static QApplication *application;

        static int argc{1};
        static std::vector<char *> argv{strdup("saucer")};

        if (!application)
        {
#ifndef SAUCER_TESTS
            qputenv("QT_LOGGING_RULES", "*=false");
#endif
            // ---------------------------------------------------------------------------------------------------------
            // I added --disable-gpu-vsync --disable-frame-rate-limit
            // yes it works, fps is no longer 60
            // ---------------------------------------------------------------------------------------------------------

            if (options.hardware_acceleration)
            {
                qputenv("QTWEBENGINE_CHROMIUM_FLAGS",
                        "--enable-oop-rasterization --disable-gpu-vsync --disable-frame-rate-limit --enable-gpu-rasterization --enable-native-gpu-memory-buffers "
                        "--use-gl=desktop");
            }

#ifdef SAUCER_QT5
            QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif
```

**Comment by daironxuan** [comment]
**Obviously, I shouldn't do this directly. In fact, there is a better way, because some machines may not need it.**

**Comment by Curve** [comment]
> **Obviously, I shouldn't do this directly. In fact, there is a better way, because some machines may not need it.**

As I've said earlier:

> I'll add a way to specify the chrome flags in the saucer::options later

**Comment by daironxuan** [comment]
## Hope it helps more people

Have some reference about Google Chrome flag options：https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md
https://www.electronjs.org/docs/all#appcommandlineappendswitchswitch-value
More configurations https://peter.sh/experiments/chromium-command-line-switches/

**Comment by Curve** [comment]
Can now be achieved by instantiating the `smartview` as following:

```cpp
saucer::smartview smartview{{.chrome_flags = {"--disable-gpu-vsync", "--disable-frame-rate-limit"}};
```

**Comment by daironxuan** [comment]
**Great！**
