### ISSUE TITLE
Do you need to get the parent window pointer?

### ISSUE THREAD

**Issue by daironxuan** [saucer/saucer#18]
### 🐛 Is your feature request related to a problem?

There are many business scenarios that require this

### 💡 Describe your idea

There are many places where members of Q Main Window are needed. Suppose: message->information. Sometimes it is not enough to rely solely on the front end.

### ❔ Describe alternatives you've considered

I think m impl ptr should be exposed

### 🤔 Additional context

> hpp

![截图 2024-03-11 03-48-12](https://github.com/saucer/saucer/assets/103756802/e7563fa1-662b-4cc0-bedd-8e5945d954ba)

> cpp

![截图 2024-03-11 03-48-12](https://github.com/saucer/saucer/assets/103756802/4f03dce8-408e-43ed-b4b5-ad0c298da2f7)

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing feature request for this issue
- [X] I've made sure that this feature is not yet implemented

**Comment by Curve** [comment]
This can already be achieved through [modules](https://saucer.github.io/docs/advanced/Modules).

**Comment by daironxuan** [comment]
> [这已经可以通过模块](https://saucer.github.io/docs/advanced/Modules)来实现。

Sorry, I forgot to see the Modules document yet, haha, Great！！！
