### ISSUE TITLE
Unable to switch the input method, Chinese cannot be input en-us OK

### ISSUE THREAD

**Issue by daironxuan** [saucer/saucer#19]
### ✍️ Bug Description

Unable to switch the input method, Chinese cannot be input but English can be input

### 🔁 Steps to reproduce

Any input box doesn't work. I'm not sure if it's a font problem, but my IBUS input method works and the Chinese font library is also installed.

### 🛸 Saucer Version

2.3.0

### 🖥️ Operating System

Linux

### 🖥️ Distribution

Ubuntu 22.04

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing bug report for this issue
- [X] the problem does occur with the reproduction steps I provided
- [X] what I described is indeed a problem

**Comment by Curve** [comment]
Please provide more information:

- Qt Version used, are you using Qt6 or Qt5?
- What input method are you using?
- How are you testing your input? On some website? If so, which?
- Any steps to reproduce?

**Comment by Curve** [comment]
https://github.com/qutebrowser/qutebrowser/issues/3761 might be related, is there any useful information for your situation?

**Comment by daironxuan** [comment]
- Qt version used, are you using Qt6 or Qt5? -> QT6
- What input method do you use? -> IBUS
- How do you test your input? On a website? If so, which one? -> any website
- Are there any steps to reproduce? How do you type Chinese characters? What does IBus have to do with this? -> Switch -between Chinese and English

https://github.com/ibus/ibus

**Comment by daironxuan** [comment]
![image](https://github.com/saucer/saucer/assets/103756802/5e6a2c8a-c73e-4ab7-93c9-ea00ac198017)

**Comment by daironxuan** [comment]
> [qutebrowser/qutebrowser#3761](https://github.com/qutebrowser/qutebrowser/issues/3761)可能相关，有适合您情况的有用信息吗？

I've looked up similar information, but I've tried updating my QT

**Comment by daironxuan** [comment]
![image](https://github.com/saucer/saucer/assets/103756802/ce33b3b9-402b-471c-af7b-8df44d7dd5a3)

**Comment by daironxuan** [comment]
Most of the problems I have collected are that lower versions of QT will have this problem. I am wondering if I should change to another QT version?
How to see it?

**Comment by Curve** [comment]
> Most of the problems I have collected are that lower versions of QT will have this problem. I am wondering if I should change to another QT version?
> How to see it?

Maybe Ibus doesn't work for Qt6, try explicity setting saucers backend to Qt5

**Comment by Curve** [comment]
> ![image](https://github.com/saucer/saucer/assets/103756802/5e6a2c8a-c73e-4ab7-93c9-ea00ac198017)
> 

Does it not work in Qt Creator as well? If so that's a Qt6 issue or an issue with your input method and not something I can change

**Comment by Curve** [comment]
https://forum.qt.io/topic/144388/qt6-5-0-and-ibus-ubuntu

I don't think this is anything I can fix, seems to be either an upstream issue or with your system

**Comment by daironxuan** [comment]
❯ qmake -v
QMake version 3.1
Using Qt version 5.15.3 in /usr/lib/x86_64-linux-gnu

It seems that QT5 will have similar problems. I will continue to try to change the version or submit a QT ISSUE

**Comment by daironxuan** [comment]
Refer to this to solve the problem -> https://forum.suse.org.cn/t/topic/16363
