### ISSUE TITLE
When the smartview is declared as global variable, `Cannot set properties of undefined (setting '_idc')` with WebView 2 

### ISSUE THREAD

**Issue by GEEKiDoS** [saucer/saucer#22]
### ✍️ Bug Description

And it is foreseeable that the saucer.call will not works
Maybe the js inject order is wrong I think?

Environment:
Windows 10 Build: 19045.4651
Edge Webview2 Version: 125.0.2535.92 

### 🔁 Steps to reproduce

Open a page and open devtools, you can see error in console
```
VM57:2  Uncaught TypeError: Cannot set properties of undefined (setting '_idc')
    at <anonymous>:2:28
```

### ❔ Expected behavior

Should not throw any error

### 👀 Screenshots

![image](https://github.com/user-attachments/assets/31b25789-4e38-4f96-b266-e0754fd11e60)

### 🛸 Saucer Version

f0a8d22

### 🖥️ Operating System

Windows 10

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing bug report for this issue
- [X] the problem does occur with the reproduction steps I provided
- [X] what I described is indeed a problem

**Comment by GEEKiDoS** [comment]
Note: I made js bridge works by manually put inject code in my page temporarily
```
interface Window {
    saucer: {
        _idc: number;
        _rpc: unknown[];
        window_edge: {
            top: number;
            bottom: number;
            left: number;
            right: number;
        },
        on_message: (msg: string) => Promise<void>;
        start_drag: () => Promise<void>;
        start_resize: (edge: number) => Promise<void>;
        call: (name: string, params: unknown[]) => Promise<unknown>;
        _resolve: (id: string, value: unknown) => Promise<void>;
    };
    chrome: any;
}

window.saucer ??= {
    _idc: 0,
    _rpc: [],
    window_edge:
    {
        top: 1,
        bottom: 2,
        left: 4,
        right: 8,
    },
    on_message: async (message: string) => {
        window.chrome.webview.postMessage(message);
    },
    start_drag: async () => {
        await window.saucer.on_message(JSON.stringify({
            ["saucer:drag"]: true
        }));
    },
    start_resize: async (edge) => {
        await window.saucer.on_message(JSON.stringify({
            ["saucer:resize"]: true,
            edge,
        }));
    },
    call: async (name, params) =>
    {
        if (!Array.isArray(params))
        {
            throw 'Bad Arguments, expected array';
        }

        if (typeof name !== 'string')
        {
            throw 'Bad Name, expected string';
        }

        const id = ++window.saucer._idc;
        
        const rtn = new Promise((resolve, reject) => {
            window.saucer._rpc[id] = {
                reject,
                resolve,
            };
        });

        await window.saucer.on_message(JSON.stringify({
                id,
                name,
                params,
        }));

        return rtn;
    },
    _resolve : async (id, value) => {
        await window.saucer.on_message(JSON.stringify({
                id,
                result: value === undefined ? null : value,
        }));
    },
};
```

**Comment by Curve** [comment]
Please show the code used

**Comment by GEEKiDoS** [comment]
> Please show the code used

Sorry for not including the code, here is it:
https://github.com/laochan-eacnet/client/blob/feature/compose-launcher/src/client/launcher/launcher.cpp#L39

**Comment by Curve** [comment]
Looks right at first glance. Is the webview created and run from the main-thread?

I'll see if the core issue is reproducible in a VM later

**Comment by GEEKiDoS** [comment]
> Looks right at first glance. Is the webview created and run from the main-thread?
> 
> I'll see if the core issue is reproducible in a VM later

Yes, it was just called from the WinMain

**Comment by Curve** [comment]
I cannot reproduce this.
I'm running Webview2 Runtime Version 126.0.2592.87 and Windows 10 (19043.1826).

This is the code used to test this:
```cpp
#include <saucer/smartview.hpp>

int main()
{
    saucer::smartview webview;

    webview.set_title("Hello World!");
    webview.set_size(500, 600);

    webview.expose("test", [](int x) { return x + 10; });

    webview.set_url("https://github.com/saucer/saucer");
    webview.set_dev_tools(true);

    webview.show();
    webview.run();

    return 0;
}
```
![image](https://github.com/user-attachments/assets/cf32bdf5-1421-4d75-967a-bb175cfdb904)

Also checked with embedding example - Works fine as well.
Maybe try updating your WebView2 Runtime?

**Comment by GEEKiDoS** [comment]
hi, I have updated the issue



发自我的iPhone


------------------ Original ------------------
From: Noah ***@***.***&gt;
Date: Thu,Jul 18,2024 5:01 PM
To: saucer/saucer ***@***.***&gt;
Cc: GEEKiDoS ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [saucer/saucer] When the smartview is declared as globalvariable, `Cannot set properties of undefined (setting '_idc')` with WebView 2 (Issue #22)

**Comment by Curve** [comment]
> hi, I have updated the issue 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Noah ***@***.***&gt; Date: Thu,Jul 18,2024 5:01 PM To: saucer/saucer ***@***.***&gt; Cc: GEEKiDoS ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [saucer/saucer] When the smartview is declared as globalvariable, `Cannot set properties of undefined (setting '_idc')` with WebView 2 (Issue #22)

What changed?

**Comment by Curve** [comment]
Ok I can recreate this with the smartview being a global variable - I'll see if this is something that I can fix or if this is a limitation with webview2.

I'd suggest making the global variable a `std::unique_ptr` instead, and initializing it from your main

**Comment by GEEKiDoS** [comment]
> Ok I can recreate this with the smartview being a global variable - I'll see if this is something that I can fix or if this is a limitation with webview2.
> 
> I'd suggest making the global variable a `std::unique_ptr` instead, and initializing it from your main

Yes, I did this and fixed that issue now

**Comment by Curve** [comment]
Ok found the issue - The init script is not initialized by the time the smartview is when it is a global variable.
I'll probably just make all the init steps `constinit`

**Comment by Curve** [comment]
This should now be fixed!

Thanks for reporting :)
