### ISSUE TITLE
[Webview2] Calling smartview.close() in exposed callback triggers assertion failed

### ISSUE THREAD

**Issue by GEEKiDoS** [saucer/saucer#24]
### ✍️ Bug Description

I'm creating my application with borderless window, so I need a api to close the window. the `window.close()` not works.
And I exposed smartview.close() to the javascript, calling it results this issue

NOTE: use `PostMessage` to close the window with `WM_CLOSE` in module works without issue

The console shows
```
Assertion failed: "Failed to execute script" && false, file E:\test\build\_deps\saucer-src\src\webview.webview2.cpp, line 329
```

### 🔁 Steps to reproduce

```cpp
saucer::smartview webview;

webview.set_title("Hello World!");
webview.set_size(500, 600);

webview.set_min_size(400, 500);
webview.set_max_size(1000, 1200);

webview.expose("close", [&webview] { webview.close(); });

webview.set_url("about:blank");
webview.set_dev_tools(true);

webview.show();
webview.run();

```
then in dev console type: 
```js
saucer.call('close', [])
```

### ❔ Expected behavior

the assertion should not be triggered

### 🛸 Saucer Version

f0a8d22

### 🖥️ Operating System

Windows 10

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing bug report for this issue
- [X] the problem does occur with the reproduction steps I provided
- [X] what I described is indeed a problem

**Comment by Curve** [comment]
Good catch! Thanks for reporting, I'm currently refactoring the windows backend a little and will address this and will issue the fix with the next release :)

**Comment by GEEKiDoS** [comment]
> Good catch! Thanks for reporting, I'm currently refactoring the windows backend a little and will address this and will issue the fix with the next release :)

Thanks for your work, This library is pretty handy for me and your response for issue is very quick

**Comment by Curve** [comment]
This is now fixed on very-experimental and should reach master quite soon :)

**Comment by Curve** [comment]
Will close this as it's fixed in `very-experimental`. The release will be a little delayed to ensure good compiler support :)
