### ISSUE TITLE
Custom Color on decorated bars (Windows)

### ISSUE THREAD

**Issue by Darleanow** [saucer/saucer#27]
### 🐛 Is your feature request related to a problem?

I don't like the idea of having to do a custom title bar to change the colour of the titlebar, or set it to dark theme, it's always white. 

![image](https://github.com/user-attachments/assets/91f37a3c-11cb-4e09-8ef0-4a5dd6112c98)

### 💡 Describe your idea

A way to change it 

### ❔ Describe alternatives you've considered

Implementing a custom titlebar

### ✅ I confirm that...

- [x] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing feature request for this issue
- [X] I've made sure that this feature is not yet implemented

**Comment by Curve** [comment]
There is no way to change the color of the title bar that is remotely portable and it simply doesn't work on Linux or MacOS for example.

You can turn the titlebar dark on windows if you enable force dark - other than that you either have to use a custom titlebar or use the module mechaism to extend it for the specific operating system where it works - of which I'm not aware of any that supports this in their standard API.

**Comment by Curve** [comment]
It seems like I forgot to merge the immersive dark mode activation for force-dark on windows in the last release. I'll double check and leave this open in the time being :)

**Comment by Darleanow** [comment]
> It seems like I forgot to merge the immersive dark mode activation for force-dark on windows in the last release. I'll double check and leave this open for the time being :)

Oh yeah sorry I forgot to mention about that !

Anyways, thanks a lot for this framework/wrapper, I'm unsure how to call it, I can make a whole C++ app with next.js as frontend, I'm forever grateful for it :D

**Comment by Curve** [comment]
> Anyways, thanks a lot for this framework/wrapper, I'm unsure how to call it, I can make a whole C++ app with next.js as frontend, I'm forever grateful for it :D

I'm glad to hear that :D

**Comment by Curve** [comment]
> It seems like I forgot to merge the immersive dark mode activation for force-dark on windows in the last release. I'll double check and leave this open for the time being :)

This is now fixed on Windows. Using force-dark properly turns the window decorations dark as well: 
![image](https://github.com/user-attachments/assets/65469667-375c-44ba-9698-8e747bebebef)

**Comment by Curve** [comment]
In case you want more control over the decoration colors you can [use a module](https://saucer.app/docs/advanced/modules) to obtain the HWND on windows and pass that to DwmSetWindowAttribute to control the decorations - I will not support fully custom colors due to portability though :)

**Comment by Darleanow** [comment]
That's fantastic man ! thanks a lot :D
