### ISSUE TITLE
Build error on windows

### ISSUE THREAD

**Issue by Zhoros** [saucer/saucer#31]
### ✍️ Bug Description

win32.utils.hpp:49:36: error: 'uint8_t' is not a member of 'std'; did you mean 'wint_t'?
   49 |     [[nodiscard]] std::vector<std::uint8_t> read(IStream *stream);
      |                                    ^~~~~~~
      |                                    wint_t
compilation terminated due to -Wfatal-errors.

### 🔁 Steps to reproduce

compile cmakelists.txt with w64-mingw, on windows.

### ❔ Expected behavior

-

### 👀 Screenshots

-

### 🛸 Saucer Version

latest release

### 🖥️ Operating System

Windows 11

### 🧰 Compiler

latest x64 mingw compiler

### 📦 Environment

none

### 🖥️ Distribution

-

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing bug report for this issue
- [X] the problem does occur with the reproduction steps I provided
- [X] what I described is indeed a problem

**Comment by Curve** [comment]
> > > w64-mingw
> > 
> > 
> > MinGW is not supported, I can fix the underlying missing header issue, however, expect to run into more issues as MinGW seems to be lacking some things like `EventRegistrationToken` iirc
> 
> Please add this to the readme.md

I'll add it to the docs when the next version releases. As far as I know you can add the required headers for `EventRegistrationToken` yourself under MinGW builds and some people have also gotten WebView2 (which is the sole culprit when it comes to MinGW support) to build with that.

See here: https://github.com/jchv/webview2-in-mingw.  
I will see if I can detect the missing headers from CMake and pull them in from some reputable source

**Comment by Curve** [comment]
> > > > > w64-mingw
> > > > 
> > > > 
> > > > MinGW is not supported, I can fix the underlying missing header issue, however, expect to run into more issues as MinGW seems to be lacking some things like `EventRegistrationToken` iirc
> > > 
> > > 
> > > Please add this to the readme.md
> > 
> > 
> > I'll add it to the docs when the next version releases. As far as I know you can add the required headers (`EventToken.h`) for `EventRegistrationToken` yourself under MinGW builds and some people have also gotten WebView2 (which is the sole culprit when it comes to MinGW support) to build with that.
> > See here: https://github.com/jchv/webview2-in-mingw. I will see if I can detect the missing headers from CMake and pull them in from some reputable source
> 
> Is there any way to build this thing through msvc build tools / commandline? Don't want to install gigabloat visual studio.

The Visual Studio Build Tools should be picked up by CMake - so yes, simply build it using CMake. Depending on what CMake defaults to, you might need to explicitly specify which generator to use via `-G`  (https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-G)

**Comment by Curve** [comment]
> I did that and it generates .sln, which usually ppl will compile with visual studio. But I'm trying to do it through my installed build tools `msbuild saucer.sln` and it ends up with tons of errors, no hope at this point. It's microsoft bullshit to get ppl install visual studio, gave up lmao.

I'll give it a shot in a VM and also look into supporting MinGW ootb. Make sure you have the Windows SDK installed.

What were the errors?

**Comment by Curve** [comment]
What MSVC version do you have?

**Comment by Curve** [comment]
You should be able to find the compiler/toolchain version in the output of `cmake --system-information`

**Comment by Curve** [comment]
> > > I did that and it generates .sln, which usually ppl will compile with visual studio. But I'm trying to do it through my installed build tools `msbuild saucer.sln` and it ends up with tons of errors, no hope at this point. It's microsoft bullshit to get ppl install visual studio, gave up lmao.
> > 
> > 
> > I'll give it a shot in a VM and also look into supporting MinGW ootb. Make sure you have the Windows SDK installed.
> > What were the errors? Afaict, the Github Workflow runners don't have the entirety of Visual Studio installed either and they build fine.
> 
> running cmake --build build yields this error
> 
> ```
> D:\apps\ctest\saucer-4.1.0\build\_deps\ereignis-src\include\ereignis\manager.hpp(50,61): error C2061: syntax error: ide
> ntifier 'type' [D:\apps\ctest\saucer-4.1.0\build\saucer.vcxproj]
>   (compiling source file '../src/window.cpp')
>   D:\apps\ctest\saucer-4.1.0\build\_deps\ereignis-src\include\ereignis\manager.hpp(50,61):
>   the template instantiation context (the oldest one first) is
>         D:\apps\ctest\saucer-4.1.0\build\_deps\ereignis-src\include\ereignis\manager.hpp(29,11):
>         while compiling class template 'ereignis::manager'
> 
> D:\apps\ctest\saucer-4.1.0\build\_deps\ereignis-src\include\ereignis\manager.hpp(50,1): error C2238: unexpected token(s
> ) preceding ';' [D:\apps\ctest\saucer-4.1.0\build\saucer.vcxproj]
>   (compiling source file '../src/window.cpp')
> ```
> 
> and 10+ more errors, no hope with this.
> 
> Github workflow might be setup in a certain way to deal with that. My error is exactly as the below. https://stackoverflow.com/questions/41695251/c-microsoft-cpp-default-props-was-not-found.

Are those the first errors that occur? I've accidentally encountered the same compilation error when another compilation unit failed

**Comment by Curve** [comment]
I've also pushed some commits to the `very-experimental` branch, among them is the fix for the initial issue regarding the missing header for `std::uint8_t`

**Comment by Curve** [comment]
Btw, if you're having trouble compiling saucer itself, you can also link against the pre-builts the workflows produce (not that I'd encourage that tho)

**Comment by Curve** [comment]
I went ahead and tested this on a VM with MSYS2, but WebView2 (upstream) depends on wrl which does not work with mingw at the moment.

I can confirm that it works with only the Visual Studio Build Tools tho - I've setup a new VM and installed the VSBuildTools with their C++ preset, building from latest master.
