### ISSUE TITLE
Add windows shadows, min/max animations etc. for frameless windows.

### ISSUE THREAD

**Issue by pivotiiii** [saucer/saucer#34]
### 🐛 Is your feature request related to a problem?

No.

### 💡 Describe your idea

When creating a window on Windows without decorations, a lot of functionality is lost. While stuff like moving, closing and resizing the window is easy enough to reimplement using just html, other functions that are integrated into Windows are not.
This includes Aero snap, window shadows, animations for minimizing and maximizing the window and much more. 
I would love for these functions to be implemented to make frameless windows not feel as if they are not part of the OS.

### 🤔 Additional context

[This is a minimal demonstration for creating a fully featured frameless window in C](https://github.com/rossy/borderless-window).
Other frameworks like Electron also handle frameless windows in a way that does not break this functionality.

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing feature request for this issue
- [X] I've made sure that this feature is not yet implemented

**Comment by Curve** [comment]
Thanks for the reference! This looks easy enough to implement, I'll probably be able to sneak this in before `v5.0.0` :)

**Comment by Curve** [comment]
I've taken a slightly different approach than in the repo you linked to keep the changes more minimal. It should work the same however, please let me know if that works for you :)

You can test this when building against `very-experimental`. Please beware, that there is a bug in the latest MSVC version which causes compilation to fail (see upstream issue: https://github.com/stephenberry/glaze/issues/1448).

The issue should be fixed in the next MSVC minor version, which will hopefully be released soon. In case you are affected by this, I'd suggest building with `clang-cl` or the last MSVC version.

**Comment by Curve** [comment]
Just tested this a little and everything seems to work as expected (Windows 11 Round Borders, Aero Snap, Animations).

I'll close this, thanks again for the suggestion, looks great!

**Comment by pivotiiii** [comment]
Everything works perfectly, thanks for adding this :)
The only thing I noticed is that HTML elements that are fixed to a side of the window (e.g. my min/max/close buttons at the top) get cut of slightly when the window gets maximized. 

Regular
![image](https://github.com/user-attachments/assets/9bc42e0c-ed08-4630-95e0-60a060373326)

Maximized
![image](https://github.com/user-attachments/assets/6dfeb3af-6c0c-499f-8ee7-be487c307fef)

When resizing the window as if it were fullscreen this doesn't happen, so I dont think it is my HTML. Maybe just something Windows does by itself? It's not a big deal though.

By the way, thanks for pointing out the MSVC bug, my stuff not building on the Github runners was driving me mad^^

**Comment by Curve** [comment]
> When resizing the window as if it were fullscreen this doesn't happen, so I dont think it is my HTML. Maybe just something Windows does by itself? It's not a big deal though.

Ah, that might be something I can fix, can you send me a short HTML snippet to reprod?

**Comment by pivotiiii** [comment]
Sure. this should work. You can maximize this by snapping it to the top.

```
<!DOCTYPE html>
<html>

<head>
    <title>Maximize Test</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
html,
body {
    height: 100vh;
    overflow: hidden;
    margin: 0px;
}

#windowBarContainer {
    height: 32px;
    width: 100%;
    background-color: darkgray;
    display: flex;
    flex-direction: row;
    justify-content: right;

#windowBarCenter {
    width: 100%;
    height: 100%;
}

.window-bar-button {
    width: 48px;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    margin-bottom: 3px;
    line-height: 100%;
}
}

    </style>
</head>

<body>
    <div id="windowBarContainer" class="window-bar">
        <div id="windowBarCenter" data-webview-drag></div>

        <div id="minButton" class="window-bar-button">-</div>
        <div id="maxButton" class="window-bar-button">O</div>
        <div id="closeButton" class="window-bar-button">X</div>
    </div>
</body>
```

**Comment by Curve** [comment]
Thanks for the snippet! This should now be fixed :)

**Comment by pivotiiii** [comment]
The top is fixed now, but the sides and bottom are still being cut off. I forgot to add something there in the snippet, sorry about that.

**Comment by Curve** [comment]
> The top is fixed now, but the sides and bottom are still being cut off. I forgot to add something there in the snippet, sorry about that.

Ah, sorry, could you edit the snippet above, I'll probably only have to subtract the respective borders there as well

**Comment by pivotiiii** [comment]
I added some purple borders on the bottom and on the sides. The top is already good as is.

```
<!DOCTYPE html>
<html>
  <head>
    <title>Maximize Test</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      html,
      body {
        height: 100vh;
        overflow: hidden;
        margin: 0px;
      }

      .window-bar {
        height: 32px;
        width: 100%;
        background-color: darkgray;
        display: flex;
        flex-direction: row;
        justify-content: right;
      }

      .window-bar-center {
        width: 100%;
        height: 100%;
      }

      .window-bar-button {
        width: 48px;
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        margin-bottom: 3px;
        line-height: 100%;
      }

      #window {
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: row;
        justify-content: center;
      }

      #windowWorkspace {
        width: 100%;
      }

      .window-edge-left {
        border-left-width: 2px;
        border-left-style: solid;
        border-left-color: blueviolet;
        width: 3px;
        height: 100%;
      }

      .window-edge-right {
        border-right-width: 2px;
        border-right-style: solid;
        border-right-color: blueviolet;
        width: 3px;
        height: 100vh;
      }

      .window-edge-bottom {
        border-bottom-width: 2px;
        border-bottom-style: solid;
        border-bottom-color: blueviolet;
        position: absolute;
        bottom: 0%;
        width: 100%;
        height: 3px;
      }
    </style>
  </head>

  <body>
    <div id="windowBarContainer" class="window-bar">
      <div
        id="windowBarCenter"
        class="window-bar-center"
        data-webview-drag
      ></div>

      <div id="minButton" class="window-bar-button">-</div>
      <div id="maxButton" class="window-bar-button">O</div>
      <div id="closeButton" class="window-bar-button">X</div>
    </div>

    <div id="window">
      <div id="resizeBarLeft" class="window-edge-left"></div>
      <div id="windowWorkspace"></div>
      <div id="resizeBarRight" class="window-edge-right"></div>
    </div>

    <div id="resizeBarBottom" class="window-edge-bottom"></div>
  </body>
</html>

```

**Comment by pivotiiii** [comment]
I also found that if you resize a window with a div that has `data-webview-resize="t"` while the window is maximized it does not properly minimize and maximize to full height again. A little bit of the original white Windows title bar that I assume gets drawn over also gets exposed and can be interacted with. Moving the window at this point hides the white title bar, but maximizing the window again returns it to the size that the maximized window was originally resized with the div to instead of full screen.

![image](https://github.com/user-attachments/assets/55e0beaf-7bc3-43b8-890e-f6d16e40d728)

To try this you can add `data-webview-resize="t"` to e.g. the min button in the last snippet and try resizing a maximized window. I am not sure if resizing should even be a thing if a window is maximized?

**Comment by pivotiiii** [comment]
> Thanks again for the snippet, should be fixed for good now :)

Looks good to me, thanks for the quick help :)

**Comment by Curve** [comment]
> I also found that if you resize a window with a div that has `data-webview-resize="t"` while the window is maximized it does not properly minimize and maximize to full height again. A little bit of the original white Windows title bar that I assume gets drawn over also gets exposed and can be interacted with. Moving the window at this point hides the white title bar, but maximizing the window again returns it to the size that the maximized window was originally resized with the div to instead of full screen.
> 
> ![image](https://private-user-images.githubusercontent.com/17112987/392456057-55e0beaf-7bc3-43b8-890e-f6d16e40d728.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjc2OTUsIm5iZiI6MTczMzMyNzM5NSwicGF0aCI6Ii8xNzExMjk4Ny8zOTI0NTYwNTctNTVlMGJlYWYtN2JjMy00M2I4LTg5MGUtZjZkMTZlNDBkNzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE1NDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMDYyMjJiZjMzMzMxYzlhZGU3OTM3NjQ3MmE1NjkxNWY3NzFjZGE5MmQwYmNlNDcwMzYxMDhlYjQ5OTAwNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wQ3hHq7SfEdJbDR_6Bj6b-gmuwuo2m6LY-5bE0dK_14)
> 
> To try this you can add `data-webview-resize="t"` to e.g. the min button in the last snippet and try resizing a maximized window. I am not sure if resizing should even be a thing if a window is maximized?

Thanks for finding all those bugs - I can reproduce this but am not sure yet how I can fix it - Windows does not give me the proper location of the window edges in time which makes this a little difficult.

**Comment by Curve** [comment]
True, I could simply restore the window when a resize is started and it is still maximized. Not sure if that would be good behavior though, if possible I'd like to solve it properly

**Comment by Curve** [comment]
Just doubled checked with the behavior on Linux, and on Linux the resize also does not exit the maximized state.

**Comment by pivotiiii** [comment]
I was thinking more along the lines of just straight up not being able to resize at all and ignoring any resize requests. No other program allows that, probably for a similar reason.

**Comment by Curve** [comment]
> I was thinking more along the lines of just straight up not being able to resize at all and ignoring any resize requests. No other program allows that, probably for a similar reason.

It's just not possible within the UI, using something like AltDrag would allow you to resize even when maximized which is why I'd like to have this fixed properly

**Comment by Curve** [comment]
I may be able to check with `isWindowArranged` or hope that I may be able to use the coordinates returned in `GetWindowPlacement` - I'll do some testing and then hopefully fix this...

**Comment by pivotiiii** [comment]
Good luck and thanks for the help. This seems like a bigger issue, so for now I will simply remove the resize attribute from the divs on maximize :)

**Comment by pivotiiii** [comment]
Hey, when trying the latest version I found that 9e6645d9d8c4a578868a490fb03bb07a6687453b broke the offset around the edges again.

**Comment by Curve** [comment]
> Hey, when trying the latest version I found that [9e6645d](https://github.com/saucer/saucer/commit/9e6645d9d8c4a578868a490fb03bb07a6687453b) broke the offset around the edges again.

Thanks for letting me know, interesting, that change was supposed to fix the border issues upon resizing. I'll investigate this

**Comment by Curve** [comment]
Please let me know if 5daeca3 fixed it :)

**Comment by pivotiiii** [comment]
It does, thank you.

**Comment by Curve** [comment]
Perfect, thanks for confirming!
