### ISSUE TITLE
Webview still active after object has been deconstructed.

### ISSUE THREAD

**Issue by pivotiiii** [saucer/saucer#35]
### ✍️ Bug Description

Hi,
in my program I create an object that holds both the app as well as the smartview variables.
When the app var is created with saucer::application::acquire, a ".saucer" folder is created in my current working directory. I want to delete that folder when my program gets closed, but there is an permission error because it is still being accessed (I checked with FileLocksmith).

I tried:
- app->quit()
- deleting the object that holds app and smartview

Before calling app->quit() there are 3 instances of webview accessing the folder, after calling it/ after deconstructing there is only one, even without anything on screen and the debugger being right on the final return. When the program returns and closes the folder can be deleted. 

Maybe an argument for the saucer::application that makes it clean up after itself would be nice.

### 🔁 Steps to reproduce

test.hpp
```
#include <saucer/smartview.hpp>

class UI {
  private:
    std::shared_ptr<saucer::application> app;
    saucer::smartview<saucer::serializers::glaze::serializer> smartview;

  public:
    UI();
    ~UI();
};

UI::UI()
    : app {saucer::application::acquire({.id = "test"})},
      smartview {{.application = app}}
{
    // 3 webviews lock the folder now
    this->smartview.set_url("https://google.com");
    this->smartview.show();

    // I only call quit directly here because in my program it is called with JS and the example still works :)
    this->app->quit(); // 3 webviews still lock the folder
}

UI::~UI()
{
}
```

test.cpp
```
#include "test.hpp"
#include "Windows.h"

int WINAPI WinMain(HINSTANCE hInt, HINSTANCE hPrevInst, LPSTR lpCmdLine, int nCmdShow)
{
    if (true) {
        auto a = UI(); // deleted when out of scope
    }
    // only 1 webview locks the folder now
    // deleting at this point would lead to a crash
    return 0; // folder is not locked after return
}
```

### ❔ Expected behavior

After calling app->quit() or after deletion of the class containing app, there should be no more webviews blocking access to the ".saucer" folder.

### 🛸 Saucer Version

v4.2.0

### 🖥️ Operating System

Windows 10

### 🧰 Compiler

MSBuild 17.10.4

### 📦 Environment

WebViev2 130.0.2849.80

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing bug report for this issue
- [X] the problem does occur with the reproduction steps I provided
- [X] what I described is indeed a problem

**Comment by Curve** [comment]
On Windows, WebView2 is used, which uses a shared WebView, which may cause the behavior you're seeing. You can change the location of the .saucer folder being created in the Webview options to e.g. some folder in `/tmp`

**Comment by pivotiiii** [comment]
Sweet thank you :)
While I got you here, I don't want to create a new issue but how would I set the application icon for the titlebar/window frame? (Not the .exe itself). I found saucer::icon but can't figure out how to make it work 😅

**Comment by Curve** [comment]
> Sweet thank you :) While I got you here, I don't want to create a new issue but how would I set the application icon for the titlebar/window frame? (Not the .exe itself). I found saucer::icon but can't figure out how to make it work 😅

You can call `set_icon` on the webview, the `saucer::icon` is creatable with `saucer::icon::from` with either a file on the filesystem or an in-memory buffer

**Comment by pivotiiii** [comment]
That'w what I tried to do, but smartview.set_icon always produces the error `no suitable user-defined conversion from "std::optional<saucer::icon>" to "const saucer::icon" exists` when using a path. Would I be able to use an embedded file for this?

**Comment by Curve** [comment]
> That'w what I tried to do, but smartview.set_icon always produces the error `no suitable user-defined conversion from "std::optional<saucer::icon>" to "const saucer::icon" exists` when using a path. Would I be able to use an embedded file for this?
> 
> Edit: Nvm I completely overlooked the `optional` part of the error, sorry for that :)

Yes, it returns an optional in case the creation failed (i.e. unsupported file-format, ...) use `.value()` to get the actual value and make sure to check if it's empty :)
