### ISSUE TITLE
Resizing window results in content moved away

### ISSUE THREAD

**Issue by atsushieno** [saucer/saucer#36]
### ✍️ Bug Description

I'm trying to use saucer on my WebView based C++ app. It seems working fine, but if I resize window on macOS the WebView content is moved. In my app (not public), the Y coordinate goes negative and cannot go back to the top of the content. It is also (likely) reproducible in the official example `examples/embedded`; it simply cleans up the content (looking like blank page) there.

It is probably specific to `wk.webview.mm` but I haven't confirmed on other platforms.

### 🔁 Steps to reproduce

on macOS, launch `examples/embedded` and resize the window.

### ❔ Expected behavior

Resizes normally.

### 👀 Screenshots

![image](https://github.com/user-attachments/assets/b78f53a1-5db0-4d13-9b24-f097ca92154a)

### 🛸 Saucer Version

7e9c730

### 🖥️ Operating System

MacOS

### 🧰 Compiler

AppleClang 16.0.0.16000026

### 📦 Environment

macOS Sonoma 14.7

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing bug report for this issue
- [X] the problem does occur with the reproduction steps I provided
- [X] what I described is indeed a problem

**Comment by Curve** [comment]
I cannot reproduce this, which WKWebView version are you running?

**Comment by atsushieno** [comment]
Not sure what is the expected answer as I don't really indicate the version of WebKit in particular, but I guess this gives the info:

```
$ head /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/WebKit.framework/Versions/Current/WebKit.tbd 
--- !tapi-tbd
tbd-version:     4
targets:         [ x86_64-macos, arm64-macos, arm64e-macos ]
install-name:    '/System/Library/Frameworks/WebKit.framework/Versions/A/WebKit'
current-version: 619.1.26
reexported-libraries:
  - targets:         [ x86_64-macos, arm64-macos, arm64e-macos ]
    libraries:       [ '/System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebKitLegacy.framework/Versions/A/WebKitLegacy', 
                       '/usr/lib/libobjc.A.dylib' ]
```

**Comment by Curve** [comment]
And this happens on the embedded example without any changes? If so, could you check if the bug also reproduces on the `very-experimental` branch?

**Comment by Curve** [comment]
Okay, apparently this is related to having the dev tools open, it seems that I'll have to set `autoresizingMask` on the webview to prevent the devtools from pushing the content oob. I'll push a fix soon.

**Comment by atsushieno** [comment]
The answers are yes, yes, yes (the same), yes (doesn't matter), and yes (doesn't matter).

**Comment by Curve** [comment]
I couldn't reproduce the issue in a new VM either, but have pushed some changes to `very-experimental`. Please let me know if that works for you :)

**Comment by atsushieno** [comment]
Yes, it works perfectly. Thanks!

**Comment by Curve** [comment]
Perfect, thanks for confirming so quickly!

**Comment by Curve** [comment]
I will release a stable version containing the fix soon!
