### ISSUE TITLE
Cli generates incorrect variable names and paths on windows 10

### ISSUE THREAD

**Issue by Xadak** [saucer/saucer#6]
I installed the saucer cli through npm. My file structure looks like this:

content
 | index.html
 | styles
 | | styles.css
 | |styles.css.map
include
...

After running `saucer embed output include/embedded content` this is the generated all.hpp file: 
```
#pragma once
#include <map>
#include <tuple>
#include <string>
#include <saucer/webview.hpp>

#include "index.html.hpp"
#include "styles\styles.css.hpp"
#include "styles\styles.css.map.hpp"

namespace embedded {
	inline auto get_all_files() {
		std::map<const std::string, const saucer::embedded_file> rtn;
		rtn.emplace("index.html", saucer::embedded_file{"text/html", 211, embedded_index_html});
		rtn.emplace("styles\styles.css", saucer::embedded_file{"text/css", 148, embedded_styles\styles_css});
		rtn.emplace("styles\styles.css.map", saucer::embedded_file{"text/plain", 141, embedded_styles\styles_css_map});
		return rtn;
	}
} // namespace embedded
```

Obviously, this does not compile, as there are variable names containing backslashes and the backslashes in the paths are not escaped properly. The same goes for all the other generated files. After manually replacing the backslashes in variable names with underscores and escaping those in the strings everything works as expected. This bug only occurs when the input folder has subdirectories, like in this case.

**Comment by Curve** [comment]
Hm, I explicitly tested for this on my Windows VM and this did not happen.  
But well we're dealing with Windows so I guess that was to be expected, I'll issue a fix as soon as possible.

Also, please for further CLI-related issues, use the issue tracker in the [saucer-cli repository](https://github.com/saucer/saucer-cli/issues) ^^

**Comment by Curve** [comment]
npm package has been updated
